EventsPlus/Controllers/EventTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventsPlus.Data;
using EventsPlus.Models;

namespace EventsPlus.Controllers
{
    public class EventTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EventTypes
        /// <summary>
        /// Gets and returns the view of the models gets the required data from the database for them
        /// </summary>
        /// <param name="sortOrder"></param>
        /// <param name="currentFilter"></param>
        /// <param name="searchString"></param>
        /// <param name="pageNumber"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
        //Sorting filtering data and logic
            ViewData["EvnTypId"] = String.IsNullOrEmpty(sortOrder) ? "evn_typ_id" : "";
            ViewData["EvnTyp"] = String.IsNullOrEmpty(sortOrder) ? "evn_typ" : "";

            var eventtype = from s in _context.EventTypes
                            select s;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
        //Filtering loogic for the search box, filters the results
            if (!String.IsNullOrEmpty(searchString))
            {
                eventtype = eventtype.Where(s => s.Id.ToString().Contains(searchString)
                                       || s.Type.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "evn_typ_id":
                    eventtype = eventtype.OrderByDescending(s => s.Id);
                    break;
                case "evn_typ":
                    eventtype = eventtype.OrderByDescending(s => s.Type);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<EventTypes>.CreateAsync(eventtype.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: EventTypes/Details/5
        /// <summary>
        /// Gets the required data from the databse for the chosen record and displays the Details view for the chosen record in the table
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventTypes = await _context.EventTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventTypes == null)
            {
                return NotFound();
            }

            return View(eventTypes);
        }

        // GET: EventTypes/Create
        /// <summary>
        /// Displays the Create view for the EventTypes
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        /// <summary>
        /// Adds the newly created record to the database based in the bind property and the model, returns to the Inedx view
        /// </summary>
        /// <param name="eventTypes"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type")] EventTypes eventTypes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventTypes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eventTypes);
        }

        // GET: EventTypes/Edit/5
        /// <summary>
        /// Displays Edit form of the chosen Id, if the Id is not found returns Id not found
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventTypes = await _context.EventTypes.FindAsync(id);
            if (eventTypes == null)
            {
                return NotFound();
            }
            return View(eventTypes);
        }

        // POST: EventTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        /// <summary>
        /// Edits the chosen record in the EventTypes table based on the Id, if the Id is not found returns not found, redirects to the Index view
        /// </summary>
        /// <param name="id"></param>
        /// <param name="eventTypes"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type")] EventTypes eventTypes)
        {
            if (id != eventTypes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventTypes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventTypesExists(eventTypes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventTypes);
        }

        // GET: EventTypes/Delete/5
        /// <summary>
        /// Displays a delete dox for the chosen record in the table based on the Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventTypes = await _context.EventTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventTypes == null)
            {
                return NotFound();
            }

            return View(eventTypes);
        }

        // POST: EventTypes/Delete/5
        /// <summary>
        /// Performs the delete action of the chosen record in the database and returns the Index View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventTypes = await _context.EventTypes.FindAsync(id);
            _context.EventTypes.Remove(eventTypes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventTypesExists(int id)
        {
            return _context.EventTypes.Any(e => e.Id == id);
        }
    }
}

EventsPlus/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventsPlus.Data;
using EventsPlus.Models;
using EventsPlus.ViewModels;

namespace EventsPlus.Controllers
{
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events 

        /// <summary>
        /// Gets and returns the view of the models gets the required data from the database for them
        /// </summary>
        /// <param name="id"></param>
        /// <param name="sortOrder"></param>
        /// <param name="searchString"></param>
        /// <param name="pageNumber"></param>
        /// <returns></returns>
        public ViewResult Index(int? id, string sortOrder, string searchString, int? pageNumber)
        {


            var viewModel = new EventAttendees();
            viewModel.Events = _context.Event
                .Include(r => r.EventType)
                .Include(p => p.Organizer)
                .Include(g => g.VenueAddress)
                .Include(p => p.GuestAttendees)
                .OrderBy(p => p.EventType);


            if (id != null)
            {
                ViewBag.Id = id.Value;
                viewModel.GuestAttendees = viewModel.Events.Where(f => f.Id == id.Value).Single().GuestAttendees;
            }
            var Events = from s in _context.Event.Include(r => r.EventType).Include(p => p.Organizer).Include(g => g.VenueAddress)
                         select s;
        //Sorting filtering data and logic
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "event_type" : "";
            ViewData["DateStartSortParm"] = sortOrder == "SDate" ? "sdate_desc" : "SDate";
            ViewData["NumOfAttendees"] = String.IsNullOrEmpty(sortOrder) ? "att_num" : "";
            ViewData["PrivSet"] = String.IsNullOrEmpty(sortOrder) ? "priv_set" : "";
            ViewData["Organizer"] = String.IsNullOrEmpty(sortOrder) ? "organizer" : "";
            ViewData["EvId"] = String.IsNullOrEmpty(sortOrder) ? "ev_id" : "";
            ViewData["VerfOnl"] = String.IsNullOrEmpty(sortOrder) ? "ver_onl" : "";
            ViewData["VenAdd"] = String.IsNullOrEmpty(sortOrder) ? "ven_add" : "";
            ViewData["DateEndSortParm"] = sortOrder == "EDate" ? "edate_desc" : "EDate";
            ViewData["CurrentFilter"] = searchString;

        //Filtering loogic for the search box, filters the results
            if (!String.IsNullOrEmpty(searchString))
            {
                viewModel.Events = viewModel.Events.Where(s => s.EventType.Type.Contains(searchString)
                || s.Organizer.OrganizerLastName.Contains(searchString)
                || s.Id.ToString().Contains(searchString)
                || s.VenueAddress.ContactAddressLine1.Contains(searchString)
                || s.NumberOfAttendies.ToString().Contains(searchString)
                || s.EventsStartTime.ToString().Contains(searchString)
                || s.EventsStartEnd.ToString().Contains(searchString));

            }
            switch (sortOrder)
            {
                case "event_type":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.EventType.Type);
                    break;
                case "organizer":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.Organizer.OrganizerLastName);
                    break;
                case "ev_id":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.Id);
                    break;
                case "att_num":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.NumberOfAttendies);
                    break;
                case "priv_set":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.PrivacySetting);
                    break;
                case "ver_onl":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.VerifiedOnly);
                    break;
                case "ven_add":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.VenueAddress.ContactAddressLine1);
                    break;
                case "SDate":
                    viewModel.Events = viewModel.Events.OrderBy(s => s.EventsStartTime);
                    break;
                case "sdate_desc":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.EventsStartTime);
                    break;
                case "EDate":
                    viewModel.Events = viewModel.Events.OrderBy(s => s.EventsStartEnd);
                    break;
                case "edate_desc":
                    viewModel.Events = viewModel.Events.OrderByDescending(s => s.EventsStartEnd);
                    break;
                default:
                    viewModel.Events = viewModel.Events.OrderBy(s => s.Organizer.OrganizerLastName);
                    break;

            }

            return View(viewModel);

        }

        // GET: Events/Details/5

        /// <summary>
        /// Gets the required data from the database for the chosen record and displays the Details view for the chosen record in the table
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(r => r.EventType)
                .Include(p => p.Organizer)
                .Include(g => g.VenueAddress)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        /// <summary>
        /// Displays the Create view for the Event
        /// </summary>
        /// <returns></returns>

        public IActionResult Create()
        {
        //Gets Ids and one mor property to be displayed and used in the drop down list
            ViewData["EventTypeId"] = new SelectList(_context.EventTypes, "Id", "Type");
            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "OrganizerLastName");
            ViewData["VenueAddressId"] = new SelectList(_context.VenueAddress, "Id", "ContactAddressLine1");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Binds the values to the model adds the record to the database, returns to the Inedx view
        /// </summary>
        /// <param name="event"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrganizerId,EventsStartTime,EventsStartEnd,NumberOfAttendies,PrivacySetting,VerifiedOnly,EventTypeId,VenueAddressId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        //Gets Ids and one mor property to be displayed and used in the drop down list.
            ViewData["EventTypeId"] = new SelectList(_context.EventTypes, "Id", "Type", @event.EventTypeId);
            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "OrganizerLastName", @event.OrganizerId);
            ViewData["VenueAddressId"] = new SelectList(_context.VenueAddress, "Id", "ContactAddressLine1", @event.VenueAddressId);
            return View(@event);
        }

        // GET: Events/Edit/5

        /// <summary>
        /// Displays Edit form of the chosen Id, if the Id is not found returns Id not found
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }

        //Gets Ids and one mor property to be displayed and used in the drop down list
            ViewData["EventTypeId"] = new SelectList(_context.EventTypes, "Id", "Type", @event.EventTypeId);
            ViewData["OrganizerId"] = new SelectList(_context.Organizer, "Id", "OrganizerLastName", @event.OrganizerId);
            ViewData["VenueAddressId"] = new SelectList(_context.VenueAddress, "Id", "ContactAddressLine1", @event.VenueAddressId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        /// <summary>
        /// Edits the chosen record in the Event table based on the Id, if the Id is not found returns not found, redirects to the Index view
        /// </summary>
        /// <param name="id"></param>
        /// <param name="event"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrganizerId,EventsStartTime,EventsStartEnd,NumberOfAttendies,PrivacySetting,VerifiedOnly,EventTypeId,VenueAddressId")] Event @event)
        {

EventsPlus/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Events Plus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/HamburgerButton.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-toggleable navbar-light py-0">
            <div class="border-bottom container">
                <div class="navbar-top-container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventsPlus</a>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                    }
                    <button 
                        class="hamburger hamburger--slider collapsed" 
                        type="button" 
                        data-toggle="collapse" 
                        data-target=".navbar-collapse" 
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" 
                        aria-label="Toggle navigation"
                    >
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Organizers" asp-action="Index">Organizers Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VenueAddresses" asp-action="Index">Venue Addresses Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EventTypes" asp-action="Index">Event Types Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GuestAttendees" asp-action="Index">Guest Attendees Manager</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="border-top container">
            &copy; 2021 - EventsPlus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>